apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rest-client
  name: rest-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-client
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rest-client
    spec:
      containers:
      - image: adaptivenetlab/rest-client:01
        name: rest-client
        resources: {}
      nodeSelector:
        kubernetes.io/hostname : worker2-sdn
status: {}
