apiVersion: v1
kind: Service
metadata:
  name: middleware-center
spec:
  selector:
    app: middleware-center
  ports:
  - name: to-flowvisor
    protocol: TCP
    port: 10002
    targetPort: 10002
  - name : port-to-ryu-app
    protocol: TCP
    port: 8080
    targetPort: 8080
