apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: middeware-center
  name: middleware-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middleware-center
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: middleware-center
    spec:
      containers:
      - image: adaptivenetlab/middleware-center:1.5
        name: middleware-center
        resources: {}
        env:
        - name: CENTER_RYU_APP
          value: ryu-app-center.default.svc.cluster.local
      nodeSelector:
        kubernetes.io/hostname : worker2-sdn
status: {}
