apiVersion: v1
kind: Service
metadata:
  name: middleware-center
spec:
  selector:
    app: middleware-center
  type: NodePort
  ports:
  - name: to-flowvisor
    protocol: TCP
    port: 10002
    targetPort: 10002
    nodePort: 31002
  - name : port-to-ryu-app
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: middeware-center
  name: middleware-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middleware-center
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: middleware-center
    spec:
      containers:
      - image: adaptivenetlab/middleware-center:1.5
        name: middleware-center
        resources: {}
        env:
        - name: CENTER_RYU_APP
          value: ryu-app-center.default.svc.cluster.local
      nodeSelector:
        kubernetes.io/hostname : worker2-sdn
status: {}
