apiVersion: v1
kind: Service
metadata:
  name: ryu-app-center
spec:
  selector:
    app: ryu-app-center
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ryu-app-center
  name: ryu-app-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ryu-app-center
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ryu-app-center
    spec:
      containers:
      - image: adaptivenetlab/ryu-app-center:sw1.0
        name: ryu-app-center
        resources: 
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        env:
        - name: CENTER_RYU_APP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CENTER_MIDDLEWARE
          value: middleware-center.default.svc.cluster.local
      nodeSelector:
        kubernetes.io/hostname : worker2-sdn
status: {}
