# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network :forwarded_port, guest: 8090, host: 8090

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y python3-pip
        pip3 install --no-cache-dir -r /vagrant/requirements.txt
    SHELL

    # python3 /vagrant/simple_switch_rest.py
end