apiVersion: v1
kind: Service
metadata:
  name: flowvisor
spec:
  selector:
    app: flowvisor
  type: NodePort
  ports:
  - protocol: TCP
    port: 6633
    targetPort: 6633
    nodePort: 30000
  - protocol: TCP
    port: 8080
    targetPort: 8080
  - protocol: TCP
    port: 8081
    targetPort: 8081