apiVersion: v1
kind: Service
metadata:
  name: middleware-left
spec:
  selector:
    app: middleware-left
  type: NodePort
  ports:
  - name: to-flowvisor
    protocol: TCP
    port: 10001
    targetPort: 10001
    nodePort: 30021 
  - name : port-to-ryu-app
    protocol: TCP
    port: 8080
    targetPort: 8080
