apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: middeware-left
  name: middleware-left
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middleware-left
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: middleware-left
    spec:
      containers:
      - image: adaptivenetlab/middleware-left:1.2
        name: middleware-left
        resources: {}
        env:
        - name: LEFT_RYU_APP
          value: ryu-app-left.default.svc.cluster.local
        volumeMounts:
        - mountPath: /usr/src/app/mount
          name: ryu-volume
      volumes:
      - name: ryu-volume
        persistentVolumeClaim:
          claimName: pv-volume-claim
      nodeSelector:
        kubernetes.io/hostname : worker2-sdn
status: {}
