apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ryu-app
  name: ryu-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ryu-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ryu-app
    spec:
      containers:
      - image: adaptivenetlab/ryu-app:02
        name: ryu-app
        resources: {}
        volumeMounts:
        - mountPath: /mnt/mounting
          name: ryu-volume
      volumes:
      - name: ryu-volume
        persistentVolumeClaim:
          claimName: pv-volume-claim
      nodeSelector:
        kubernetes.io/hostname : worker2-sdn
status: {}
