apiVersion: v1
kind: Service
metadata:
  name: ryu-app-right
spec:
  selector:
    app: ryu-app-right
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ryu-app-right
  name: ryu-app-right
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ryu-app-right
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ryu-app-right
    spec:
      containers:
      - image: adaptivenetlab/ryu-app-right:1.5
        name: ryu-app-right
        resources: 
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        env:
        - name: RIGHT_RYU_APP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: RIGHT_MIDDLEWARE
          value: middleware-right.default.svc.cluster.local
      nodeSelector:
        kubernetes.io/hostname : worker2-sdn
status: {}
