apiVersion: v1
kind: Service
metadata:
  name: middleware-mid
  namespace: comnetsemu
spec:
  selector:
    app: middleware-middle
  type: NodePort
  ports:
  - name: to-flowvisor
    protocol: TCP
    port: 10002
    targetPort: 10002
    nodePort: 30002
  - name : port-to-ryu-app
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: middeware-middle
  name: middleware-middle
  namespace: comnetsemu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middleware-middle
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: middleware-middle
    spec:
      containers:
      - image: adaptivenetlab/middleware-middle:1.0
        name: middleware-middle
        resources: 
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        env:
        - name: MIDDLE_RYU_APP
          value: ryu-app-middle.comnetsemu.svc.cluster.local
      nodeSelector:
        kubernetes.io/hostname : worker1-sdn
status: {}
