apiVersion: v1
kind: Service
metadata:
  name: middleware-lower
  namespace: comnetsemu
spec:
  selector:
    app: middleware-lower
  type: NodePort
  ports:
  - name: to-flowvisor
    protocol: TCP
    port: 10003
    targetPort: 10003
    nodePort: 30003
  - name : port-to-ryu-app
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: middeware-lower
  name: middleware-lower
  namespace: comnetsemu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middleware-lower
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: middleware-lower
    spec:
      containers:
      - image: adaptivenetlab/middleware-lower:1.0
        name: middleware-lower
        resources: 
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        env:
        - name: LOWER_RYU_APP
          value: ryu-app-lower.comnetsemu.svc.cluster.local
      nodeSelector:
        kubernetes.io/hostname : worker1-sdn
status: {}
