apiVersion: v1
kind: Service
metadata:
  name: ryu-app-lower
  namespace: comnetsemu
spec:
  selector:
    app: ryu-app-lower
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ryu-app-lower
  name: ryu-app-lower
  namespace: comnetsemu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ryu-app-lower
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ryu-app-lower
    spec:
      containers:
      - image: adaptivenetlab/ryu-app-lower:1.0
        name: ryu-app-lower
        resources: 
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        env:
        - name: LOWER_RYU_APP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: LOWER_MIDDLEWARE
          value: middleware-lower.comnetsemu.svc.cluster.local
      nodeSelector:
        kubernetes.io/hostname : worker2-sdn
status: {}
