apiVersion: v1
kind: Service
metadata:
  name: flowvisor-comnetsemu
  namespace: comnetsemu
spec:
  selector:
    app: flowvisor-comnetsemu
  type: NodePort
  ports:
  - name: expose-6633
    protocol: TCP
    port: 6633
    targetPort: 6633
    nodePort: 30000
  - name: expose-8080
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: expose-8081
    protocol: TCP
    port: 8081
    targetPort: 8081
